#!/bin/sh
#
# Licensed under the Universal Permissive License (UPL), Version 1.0.
# See LICENSE.txt for details.

# Source function library.
. /etc/rc.d/init.d/functions

uid=$(id -u)

case "$1" in
  start)
	[ -x /usr/sbin/fdrd ] || exit 5

	# Only root can start the service
	[ "$uid" -ne 0 ] && exit 4

	# Prefer tracefs; fall back to debugfs on older systems.
	tpath=$(awk '$3 == "tracefs" { print $2; exit }' /proc/mounts)
	if [ -z "$tpath" ]; then
		tpath=$(awk '$3 == "debugfs" { print $2; exit }' /proc/mounts)
		[ -n "$tpath" ] && tpath="$tpath/tracing"
	fi
	[ -z "$tpath" ] && mount -t tracefs nodev /sys/kernel/tracing 2>/dev/null
	tpath=$(awk '$3 == "tracefs" { print $2; exit }' /proc/mounts)
	[ -z "$tpath" ] && exit 5

	action $"Starting fdr services "
	daemon fdrd -d "$tpath" 2> /var/log/fdr.log
	RETVAL=$?
	echo
	;;
  stop)
	# Only root can stop the service
	[ "$uid" -ne 0 ] && exit 4

	# Stop daemons.
	echo -n $"Shutting down fdr daemon: "
	killproc fdrd -15
	RETVAL=$?
	echo
	;;
  status)
	status fdrd
	RETVAL=$?
	;;
  restart )
	$0 stop
	$0 start
	RETVAL=$?
	echo
	;;
  reload)
	[ "$uid" -ne 0 ] && exit 4
	killproc fdrd -HUP
	RETVAL=$?
	;;
  *)
	echo $"Usage: fdr {start|stop|status|restart|reload}"
	RETVAL=2
	;;
esac

exit $RETVAL
