#!/bin/sh
set -eu

cluster_name=${FDR_LAB_CLUSTER:-fdr-lab}
cluster_context="kind-${cluster_name}"
fdr_namespace=${FDR_LAB_NAMESPACE:-fdr-lab}
monitoring_namespace=${FDR_LAB_MONITORING_NAMESPACE:-monitoring}
monitoring_release=${FDR_LAB_MONITORING_RELEASE:-monitoring}
monitoring_chart_version=88.5.4
monitoring_repo_url=https://prometheus-community.github.io/helm-charts
monitoring_timeout=${FDR_LAB_MONITORING_TIMEOUT:-10m}
image_pull_timeout=${FDR_LAB_IMAGE_PULL_TIMEOUT:-15m}
fdr_image=fdr-lab:dev
grafana_port=${FDR_LAB_GRAFANA_PORT:-13000}
prometheus_port=${FDR_LAB_PROMETHEUS_PORT:-19090}

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../.." && pwd)
artifacts_root="$repo_root/.build/fdr-lab-artifacts"
cluster_owner_file="$artifacts_root/${cluster_name}.owned"
monitoring_cache="$artifacts_root/cache"
monitoring_chart="$monitoring_cache/kube-prometheus-stack-${monitoring_chart_version}.tgz"
forward_pid=
active_run_dir=
run_results=
temporary_files=

# Exact images rendered or generated by kube-prometheus-stack 88.5.4 with the
# focused deploy/kind/monitoring-values.yaml profile.
monitoring_images='
quay.io/kiwigrid/k8s-sidecar:2.10.1
docker.io/grafana/grafana:11.5.2
quay.io/prometheus-operator/prometheus-operator:v0.93.1
quay.io/prometheus-operator/prometheus-config-reloader:v0.93.1
docker.io/prom/prometheus:v3.5.0
'

say()
{
	printf '%s\n' "$*"
}

fail()
{
	printf 'error: %s\n' "$*" >&2
	exit 1
}

require_command()
{
	command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

require_tools()
{
	for tool in curl docker findmnt git helm jq kind kubectl mktemp timeout; do
		require_command "$tool"
	done
}

require_screenshot_tools()
{
	require_command playwright
}

retry()
{
	max_attempts=$1
	shift
	attempt=1
	while ! "$@"; do
		if [ "$attempt" -ge "$max_attempts" ]; then
			return 1
		fi
		attempt=$((attempt + 1))
		say "Retrying ($attempt/$max_attempts): $*"
		sleep 5
	done
}

require_acknowledgement()
{
	if [ "${FDR_LAB_ACKNOWLEDGE_HOST_KERNEL:-}" != "yes" ]; then
		fail "set FDR_LAB_ACKNOWLEDGE_HOST_KERNEL=yes after reading deploy/kind/README.md"
	fi
}

cluster_exists()
{
	kind get clusters 2>/dev/null | grep -Fxq "$cluster_name"
}

lab_worker_node()
{
	kind get nodes --name "$cluster_name" | grep worker | head -n 1
}

trace_instance_exists()
{
	worker_node=$(lab_worker_node)
	[ -n "$worker_node" ] || return 1
	docker exec "$worker_node" test -d /sys/kernel/tracing/instances/fdr-lab
}

use_context()
{
	kubectl config use-context "$cluster_context" >/dev/null
}

prepare_monitoring_chart()
{
	mkdir -p "$monitoring_cache"
	repo_url=$(helm repo list -o json 2>/dev/null | jq -r \
	    'map(select(.name == "prometheus-community"))[0].url // ""' || true)
	if [ "$repo_url" = "$monitoring_repo_url" ]; then
		say "Using configured prometheus-community Helm repository"
	else
		retry 3 helm repo add prometheus-community "$monitoring_repo_url" \
		    --force-update
	fi
	if [ ! -s "$monitoring_chart" ]; then
		say "Caching kube-prometheus-stack chart $monitoring_chart_version"
		retry 3 helm pull prometheus-community/kube-prometheus-stack \
		    --version "$monitoring_chart_version" \
		    --destination "$monitoring_cache"
	fi
	helm show chart "$monitoring_chart" >/dev/null
}

load_monitoring_images()
{
	architecture=$(kubectl get nodes \
	    -o jsonpath='{.items[0].status.nodeInfo.architecture}')
	for image in $monitoring_images; do
		if docker image inspect "$image" >/dev/null 2>&1; then
			say "Using cached image $image"
		else
			say "Pulling monitoring image $image"
			retry 3 timeout "$image_pull_timeout" docker pull \
			    --platform "linux/$architecture" "$image"
		fi
		load_docker_image "$image"
	done
}

load_docker_image()
{
	image=$1
	architecture=$(kubectl get nodes \
	    -o jsonpath='{.items[0].status.nodeInfo.architecture}')
	nodes_to_load=
	for node in $(kind get nodes --name "$cluster_name"); do
		if ! docker exec "$node" crictl inspecti "$image" >/dev/null 2>&1; then
			nodes_to_load="$nodes_to_load $node"
		fi
	done
	if [ -z "$nodes_to_load" ]; then
		say "Image already loaded in Kind: $image"
		return
	fi

	archive=$(mktemp "$monitoring_cache/image.XXXXXX.tar")
	if ! docker save --output "$archive" "$image"; then
		rm -f "$archive"
		return 1
	fi
	for node in $nodes_to_load; do
		say "Loading $image into $node"
		if ! docker exec --privileged -i "$node" \
		    ctr --namespace=k8s.io images import \
		    --platform "linux/$architecture" --digests \
		    --snapshotter=overlayfs - <"$archive"; then
			rm -f "$archive"
			return 1
		fi
	done
	rm -f "$archive"
}

wait_for_http()
{
	url=$1
	attempt=0
	while ! curl --fail --silent --show-error "$url" >/dev/null 2>&1; do
		attempt=$((attempt + 1))
		if [ "$attempt" -ge 60 ]; then
			return 1
		fi
		sleep 1
	done
}

stop_forward()
{
	forward_pid=$1
	if kill -0 "$forward_pid" 2>/dev/null; then
		kill "$forward_pid" 2>/dev/null || true
		wait "$forward_pid" 2>/dev/null || true
	fi
}

cleanup_forward()
{
	if [ -n "$forward_pid" ]; then
		stop_forward "$forward_pid"
		forward_pid=
	fi
}

cleanup_temporary_files()
{
	for temporary_file in $temporary_files; do
		rm -f "$temporary_file"
	done
	temporary_files=
}

record_result()
{
	name=$1
	detail=$2
	[ -n "$run_results" ] || return 0
	printf '%s|PASS|%s\n' "$name" "$detail" >>"$run_results"
}

begin_run()
{
	timestamp=$(date -u +%Y%m%dT%H%M%SZ)
	active_run_dir="$artifacts_root/runs/$timestamp"
	mkdir -p "$active_run_dir/screenshots"
	run_results="$active_run_dir/results.txt"
	: >"$run_results"
}

write_report()
{
	status=$1
	report="$active_run_dir/report.md"
	commit=$(git -C "$repo_root" rev-parse HEAD 2>/dev/null || printf unknown)
	kernel=$(uname -srmo)
	cat >"$report" <<EOF
# FDR Kind smoke-test report

- Status: **$status**
- UTC run: $(basename "$active_run_dir")
- Commit: \`$commit\`
- Host kernel: \`$kernel\`
- Kind: \`$(kind version 2>/dev/null | head -n 1)\`
- Kubernetes: \`$(kubectl version --client -o json 2>/dev/null | jq -r '.clientVersion.gitVersion // "unknown"')\`
- Container runtime: Docker \`$(docker version --format '{{.Server.Version}}' 2>/dev/null || printf unknown)\`

## Checks

| Check | Result | Evidence |
|---|---|---|
EOF
	while IFS='|' read -r name result detail; do
		printf '| %s | %s | %s |\n' "$name" "$result" "$detail" >>"$report"
	done <"$run_results"
	cat >>"$report" <<EOF

## Screenshots

EOF
	for screenshot in grafana-healthy grafana-degraded prometheus-targets; do
		if [ -s "$active_run_dir/screenshots/$screenshot.png" ]; then
			printf -- '- [%s](screenshots/%s.png)\n' "$screenshot" "$screenshot" \
			    >>"$report"
		fi
	done
	cat >>"$report" <<EOF

Raw Kubernetes, tracefs, metrics, capture, and log evidence is stored beside
this report. A local Kind pass validates one host kernel; it does not replace
the multi-kernel disposable-VM matrix or controlled-load benchmarks.
EOF
}

collect_into()
{
	destination=$1
	mkdir -p "$destination"
	use_context

	{
		uname -a
		printf '\nHost OS:\n'
		cat /etc/os-release
		printf '\nCPU count: '
		getconf _NPROCESSORS_ONLN
		printf 'Cgroup filesystem: '
		findmnt -n -o FSTYPE -T /sys/fs/cgroup
		printf 'Root filesystem: '
		findmnt -n -o FSTYPE -T /
		docker version
		kind version
		kubectl version -o yaml
		helm version
		git -C "$repo_root" status --short --branch
		git -C "$repo_root" rev-parse HEAD
		docker image inspect "$fdr_image" --format 'image_id={{.Id}} created={{.Created}}'
	} >"$destination/environment.txt" 2>&1 || true
	kubectl get nodes -o wide >"$destination/nodes.txt" 2>&1 || true
	kubectl get all -A -o wide >"$destination/all-resources.txt" 2>&1 || true
	kubectl get events -A --sort-by=.lastTimestamp >"$destination/events.txt" 2>&1 || true
	kubectl -n "$fdr_namespace" describe daemonset fdr-lab \
	    >"$destination/fdr-daemonset.txt" 2>&1 || true
	kubectl -n "$fdr_namespace" logs daemonset/fdr-lab -c fdrd \
	    >"$destination/fdr.log" 2>&1 || true
	kubectl -n "$fdr_namespace" logs daemonset/fdr-lab \
	    -c tracefs-preflight >"$destination/preflight.log" 2>&1 || true
	kubectl -n "$fdr_namespace" get networkpolicy \
	    -o yaml >"$destination/fdr-networkpolicy.yaml" 2>&1 || true
	kubectl -n "$monitoring_namespace" get podmonitor,prometheusrule,configmap \
	    -l app.kubernetes.io/instance=fdr-lab -o yaml \
	    >"$destination/fdr-observability.yaml" 2>&1 || true
	kubectl -n "$fdr_namespace" exec daemonset/fdr-lab -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/metrics \
	    >"$destination/fdr-metrics.txt" 2>&1 || true
	kubectl -n "$fdr_namespace" exec daemonset/fdr-lab -c fdrd -- \
	    sh -ec 'for file in /var/log/fdr/lab.log /var/log/fdr/lab.log.1; do
	      [ -e "$file" ] || continue
	      stat -c "%F %a %s %n" "$file"
	      tail -n 10 "$file"
	    done' >"$destination/capture-sample.txt" 2>&1 || true
	worker_node=$(kind get nodes --name "$cluster_name" | grep worker | head -n 1)
	if [ -n "$worker_node" ]; then
		docker exec "$worker_node" sh -ec \
		    'uname -a; findmnt -T /sys/kernel/tracing; ls -ld /sys/kernel/tracing/instances; ls -la /sys/kernel/tracing/instances/fdr-lab 2>/dev/null || true' \
		    >"$destination/tracefs-state.txt" 2>&1 || true
	fi
	kind export logs --name "$cluster_name" "$destination/kind" \
	    >/dev/null 2>&1 || true
}

capture_page()
{
	url=$1
	output=$2
	playwright screenshot --browser chromium --viewport-size "1440,1000" \
	    --wait-for-timeout 8000 --full-page "$url" "$output" >/dev/null
	[ -s "$output" ] || fail "screenshot was not created: $output"
}

failed_run()
{
	rc=$?
	trap - 0 1 2 15
	cleanup_forward
	cleanup_temporary_files
	if [ -n "$active_run_dir" ] && cluster_exists; then
		say "Smoke test failed; collecting diagnostics before returning"
		collect_into "$active_run_dir"
		write_report FAILED
		say "Artifacts: $active_run_dir"
	fi
	exit "$rc"
}

collect()
{
	require_tools
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	timestamp=$(date -u +%Y%m%dT%H%M%SZ)
	destination="$artifacts_root/$timestamp"
	collect_into "$destination"
	say "Artifacts: $destination"
}

verify_core()
{
	use_context
	mkdir -p "$artifacts_root"

	say "Waiting for FDR DaemonSet"
	kubectl -n "$fdr_namespace" rollout status daemonset/fdr-lab --timeout=180s
	pod=$(fdr_pod)
	[ -n "$pod" ] || fail "FDR pod was not found"

	say "Checking health, readiness, and metrics"
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/healthz | grep -Fxq ok
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/readyz | grep -Fxq ready
	metrics=$(kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/metrics)
	printf '%s\n' "$metrics" | grep -q '^fdr_ready 1$'
	printf '%s\n' "$metrics" | grep -q '^fdr_trace_overruns_total '
	printf '%s\n' "$metrics" | grep -q '^fdr_trace_dropped_events_total '
	printf '%s\n' "$metrics" | grep -q '^fdr_trace_commit_overruns_total '

	say "Checking real trace output"
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- sh -ec '
	  attempt=0
	  while [ ! -s /var/log/fdr/lab.log ]; do
	    attempt=$((attempt + 1))
	    [ "$attempt" -lt 30 ] || exit 1
	    find /etc/fdr.d -maxdepth 1 -type f >/dev/null
	    sleep 1
	  done
	  grep -Eq "sched_(switch|wakeup)" /var/log/fdr/lab.log
	'

	trace_instance_exists ||
	    fail "host trace instance was not created"
	record_result "Real trace capture" "scheduler events reached a regular capture file"

	say "Checking Prometheus discovery and rules"
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-kube-prometheus-prometheus \
	    "$prometheus_port:9090" >"$artifacts_root/prometheus-port-forward.log" 2>&1 &
	forward_pid=$!
	if ! wait_for_http "http://127.0.0.1:$prometheus_port/-/ready"; then
		stop_forward "$forward_pid"
		fail "Prometheus port-forward did not become ready"
	fi
	result=$(curl --fail --silent --get \
	    --data-urlencode "query=fdr_ready{pod=\"$pod\"} == 1" \
	    "http://127.0.0.1:$prometheus_port/api/v1/query")
	attempt=0
	while ! printf '%s' "$result" | jq -e \
	    '.status == "success" and (.data.result | length) > 0' >/dev/null; do
		attempt=$((attempt + 1))
		[ "$attempt" -lt 90 ] || fail "Prometheus did not discover the FDR target"
		sleep 2
		result=$(curl --fail --silent --get \
		    --data-urlencode "query=fdr_ready{pod=\"$pod\"} == 1" \
		    "http://127.0.0.1:$prometheus_port/api/v1/query")
	done
	attempt=0
	while :; do
		rules=$(curl --fail --silent \
		    "http://127.0.0.1:$prometheus_port/api/v1/rules")
		printf '%s' "$rules" | jq -e \
		    '.data.groups | any(.name == "fdr.rules")' >/dev/null && break
		attempt=$((attempt + 1))
		[ "$attempt" -lt 90 ] || fail "Prometheus did not load fdr.rules"
		sleep 2
	done
	if [ -n "$active_run_dir" ]; then
		capture_page "http://127.0.0.1:$prometheus_port/targets?search=podMonitor%2Fmonitoring%2Ffdr-lab" \
		    "$active_run_dir/screenshots/prometheus-targets.png"
	fi
	stop_forward "$forward_pid"
	forward_pid=
	record_result "Prometheus discovery" "FDR target and fdr.rules group discovered"

	say "Checking Grafana dashboard provisioning"
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-grafana "$grafana_port:80" \
	    >"$artifacts_root/grafana-port-forward.log" 2>&1 &
	forward_pid=$!
	if ! wait_for_http "http://127.0.0.1:$grafana_port/api/health"; then
		stop_forward "$forward_pid"
		fail "Grafana port-forward did not become ready"
	fi
	dashboards=$(curl --fail --silent --user admin:fdr-lab \
	    "http://127.0.0.1:$grafana_port/api/search?query=FDR")
	printf '%s' "$dashboards" | jq -e \
	    'any(.uid == "fdr-kernel-recorder")' >/dev/null
	if [ -n "$active_run_dir" ]; then
		capture_page "http://127.0.0.1:$grafana_port/d/fdr-kernel-recorder/fdr-kernel-flight-recorder?orgId=1&from=now-15m&to=now&var-namespace=$fdr_namespace&var-pod=$pod&refresh=5s&kiosk" \
		    "$active_run_dir/screenshots/grafana-healthy.png"
	fi
	stop_forward "$forward_pid"
	forward_pid=
	record_result "Grafana provisioning" "dashboard UID fdr-kernel-recorder is available"

	say "LAB PASS: FDR captured real host-kernel events and is visible in Prometheus and Grafana"
}

verify()
{
	require_tools
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	trap cleanup_forward 0 1 2 15
	verify_core
	trap - 0 1 2 15
}

new_config_file()
{
	mode=$1
	config_file=$(mktemp "$artifacts_root/config.XXXXXX")
	temporary_files="$temporary_files $config_file"
	case $mode in
	valid)
		cat >"$config_file" <<EOF
instance fdr-lab 4m
enable sched/sched_wakeup
minfree 5
saveto /var/log/fdr/lab.log 16m
# smoke rollout $(date -u +%Y%m%dT%H%M%SZ)
EOF
		;;
	degraded)
		cat >"$config_file" <<EOF
instance fdr-lab 4m
enable sched/fdr_smoke_event_does_not_exist
minfree 5
saveto /var/log/fdr/lab.log 16m
EOF
		;;
	*) fail "unknown smoke configuration: $mode" ;;
	esac
}

fdr_pod()
{
	kubectl -n "$fdr_namespace" get pods \
	    -l app.kubernetes.io/instance=fdr-lab \
	    -o json | jq -r '
	      [.items[] | select(.metadata.deletionTimestamp == null)] |
	      sort_by(.metadata.creationTimestamp) | last | .metadata.name // empty'
}

wait_for_new_running_pod()
{
	old_pod=$1
	attempt=0
	while :; do
		pod=$(fdr_pod)
		phase=$(kubectl -n "$fdr_namespace" get pod "$pod" \
		    -o jsonpath='{.status.phase}' 2>/dev/null || true)
		if [ -n "$pod" ] && [ "$pod" != "$old_pod" ] && [ "$phase" = Running ]; then
			printf '%s\n' "$pod"
			return 0
		fi
		attempt=$((attempt + 1))
		[ "$attempt" -lt 90 ] || return 1
		sleep 2
	done
}

helm_apply_config()
{
	config_file=$1
	wait_mode=$2
	if [ "$wait_mode" = wait ]; then
		helm upgrade fdr-lab "$repo_root/deploy/helm/fdr" \
		    --namespace "$fdr_namespace" \
		    --values "$script_dir/fdr-values.yaml" \
		    --set-file "config.lab\\.conf=$config_file" \
		    --wait --timeout 5m
		kubectl -n "$fdr_namespace" rollout status daemonset/fdr-lab \
		    --timeout=180s
	else
		helm upgrade fdr-lab "$repo_root/deploy/helm/fdr" \
		    --namespace "$fdr_namespace" \
		    --values "$script_dir/fdr-values.yaml" \
		    --set-file "config.lab\\.conf=$config_file"
	fi
}

capture_degraded_dashboard()
{
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-kube-prometheus-prometheus \
	    "$prometheus_port:9090" >"$active_run_dir/prometheus-degraded-forward.log" 2>&1 &
	forward_pid=$!
	wait_for_http "http://127.0.0.1:$prometheus_port/-/ready" ||
	    fail "Prometheus port-forward did not become ready"
	attempt=0
	while :; do
		result=$(curl --fail --silent --get \
		    --data-urlencode "query=fdr_ready{pod=\"$degraded_pod\"} == 0" \
		    "http://127.0.0.1:$prometheus_port/api/v1/query")
		printf '%s' "$result" | jq -e \
		    '.status == "success" and (.data.result | length) > 0' >/dev/null && break
		attempt=$((attempt + 1))
		[ "$attempt" -lt 30 ] || fail "Prometheus did not observe degraded readiness"
		sleep 2
	done
	# Give the 15-second scrape interval a second sample so Grafana range
	# queries render the zero value instead of treating the new series as empty.
	sleep 20
	stop_forward "$forward_pid"
	forward_pid=

	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-grafana "$grafana_port:80" \
	    >"$active_run_dir/grafana-degraded-forward.log" 2>&1 &
	forward_pid=$!
	wait_for_http "http://127.0.0.1:$grafana_port/api/health" ||
	    fail "Grafana port-forward did not become ready"
	capture_page "http://127.0.0.1:$grafana_port/d/fdr-kernel-recorder/fdr-kernel-flight-recorder?orgId=1&from=now-15m&to=now&var-namespace=$fdr_namespace&var-pod=$degraded_pod&refresh=5s&kiosk" \
	    "$active_run_dir/screenshots/grafana-degraded.png"
	stop_forward "$forward_pid"
	forward_pid=
}

smoke()
{
	require_tools
	require_screenshot_tools
	require_acknowledgement
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	if [ -z "$active_run_dir" ]; then
		begin_run
	fi
	trap failed_run 0 1 2 15
	use_context

	if [ ! -s "$run_results" ]; then
		verify_core
	fi

	say "Checking ConfigMap-driven controlled rollout"
	old_pod=$(fdr_pod)
	new_config_file valid
	valid_config=$config_file
	helm_apply_config "$valid_config" wait
	new_pod=$(fdr_pod)
	[ "$new_pod" != "$old_pod" ] || fail "configuration change did not replace the pod"
	kubectl -n "$fdr_namespace" get configmap fdr-lab-config -o yaml |
	    grep -q 'smoke rollout'
	record_result "Configuration rollout" "ConfigMap checksum replaced $old_pod with $new_pod"

	say "Checking unavailable-probe degraded readiness"
	new_config_file degraded
	degraded_config=$config_file
	old_pod=$new_pod
	helm_apply_config "$degraded_config" no-wait
	degraded_pod=$(wait_for_new_running_pod "$old_pod") ||
	    fail "degraded FDR pod did not start"
	attempt=0
	while ! kubectl -n "$fdr_namespace" exec "$degraded_pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/healthz >/dev/null 2>&1; do
		attempt=$((attempt + 1))
		[ "$attempt" -lt 60 ] || fail "degraded pod health endpoint did not start"
		sleep 1
	done
	if kubectl -n "$fdr_namespace" exec "$degraded_pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/readyz >/dev/null 2>&1; then
		fail "unavailable probe did not degrade readiness"
	fi
	kubectl -n "$fdr_namespace" exec "$degraded_pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/metrics |
	    grep -Eq '^fdr_probe_failures_total [1-9][0-9]*$'
	capture_degraded_dashboard
	record_result "Probe degradation" "missing tracepoint kept liveness healthy and readiness false"

	say "Restoring valid configuration"
	helm_apply_config "$valid_config" wait
	pod=$(fdr_pod)

	say "Checking persistent collector supervision and pod recovery"
	restart_before=$(kubectl -n "$fdr_namespace" get pod "$pod" \
	    -o jsonpath='{.status.containerStatuses[?(@.name=="fdrd")].restartCount}')
	worker_pid=$(kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- sh -ec '
	  for candidate in $(pidof fdrd); do
	    if [ "$candidate" -ne 1 ]; then
	      printf "%s\n" "$candidate"
	      exit 0
	    fi
	  done
	  exit 1
	')
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    kill -TERM "$worker_pid" || true
	attempt=0
	while :; do
		restart_after=$(kubectl -n "$fdr_namespace" get pod "$pod" \
		    -o jsonpath='{.status.containerStatuses[?(@.name=="fdrd")].restartCount}' \
		    2>/dev/null || printf 0)
		if [ "$restart_after" -gt "$restart_before" ]; then
			kubectl -n "$fdr_namespace" wait --for=condition=Ready \
			    "pod/$pod" --timeout=180s
			break
		fi
		attempt=$((attempt + 1))
		[ "$attempt" -lt 90 ] || fail "pod did not recover after collector termination"
		sleep 2
	done
	kubectl -n "$fdr_namespace" logs "$pod" -c fdrd --previous \
	    >"$active_run_dir/worker-previous.log"
	grep -q 'unexpectedly' "$active_run_dir/worker-previous.log"
	record_result "Collector recovery" "worker termination caused container restart $restart_before -> $restart_after"

	say "Checking bounded fallback rotation and file permissions"
	rotations_before=$(kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/metrics | \
	    awk '$1 == "fdr_rotations_total" { print $2 }')
	attempt=0
	while :; do
		rotations_after=$(kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
		    curl --fail --silent http://127.0.0.1:9119/metrics | \
		    awk '$1 == "fdr_rotations_total" { print $2 }')
		if [ "$rotations_after" -gt "$rotations_before" ] && \
		    kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    sh -ec '[ -f /var/log/fdr/lab.log ] && [ ! -L /var/log/fdr/lab.log ] &&
	      [ -s /var/log/fdr/lab.log ] && [ -f /var/log/fdr/lab.log.1 ] &&
	      [ ! -L /var/log/fdr/lab.log.1 ] && [ -s /var/log/fdr/lab.log.1 ] &&
	      [ "$(stat -c %a /var/log/fdr/lab.log)" = 600 ] &&
	      [ "$(stat -c %a /var/log/fdr/lab.log.1)" = 600 ]' >/dev/null 2>&1; then
			break
		fi
		kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- sh -ec '
		  i=0
		  while [ "$i" -lt 500 ]; do
		    sh -c :
		    i=$((i + 1))
		  done
		' >/dev/null
		attempt=$((attempt + 1))
		[ "$attempt" -lt 60 ] || fail "capture did not rotate with expected files and modes"
		sleep 1
	done
	record_result "Capture rotation" "rotation count increased $rotations_before -> $rotations_after; current and preserved files are regular, non-empty, and mode 0600"

	collect_into "$active_run_dir"
	write_report PASSED
	cleanup_temporary_files
	trap - 0 1 2 15
	say "SMOKE PASS: rollout, degradation, recovery, rotation, and screenshots verified"
	say "Artifacts: $active_run_dir"
}

up()
{
	require_tools
	require_acknowledgement
	[ "$(findmnt -n -o FSTYPE -T /sys/kernel/tracing)" = "tracefs" ] ||
	    fail "/sys/kernel/tracing is not a tracefs mount"
	tracefs_options=$(findmnt -n -o OPTIONS -T /sys/kernel/tracing)
	printf '%s\n' "$tracefs_options" | tr ',' '\n' | grep -Fxq rw ||
	    fail "/sys/kernel/tracing is not mounted read-write"
	mkdir -p "$artifacts_root"

	say "Building local image $fdr_image"
	docker build --provenance=false -t "$fdr_image" \
	    -f "$repo_root/deploy/kubernetes/Dockerfile" "$repo_root"
	prepare_monitoring_chart

	if ! cluster_exists; then
		say "Creating Kind cluster $cluster_name"
		kind create cluster --name "$cluster_name" \
		    --config "$script_dir/kind-config.yaml" --wait 180s
		touch "$cluster_owner_file"
	else
		if [ ! -f "$cluster_owner_file" ] &&
		    [ "${FDR_LAB_REUSE_EXISTING:-}" != "yes" ]; then
			fail "cluster $cluster_name already exists; set FDR_LAB_REUSE_EXISTING=yes to use it without ownership"
		fi
		say "Using existing Kind cluster $cluster_name"
	fi
	use_context
	load_docker_image "$fdr_image"
	load_monitoring_images

	say "Installing kube-prometheus-stack $monitoring_chart_version"
	helm upgrade --install "$monitoring_release" \
	    "$monitoring_chart" \
	    --namespace "$monitoring_namespace" --create-namespace \
	    --values "$script_dir/monitoring-values.yaml" \
	    --wait --timeout "$monitoring_timeout"

	say "Installing FDR"
	helm upgrade --install fdr-lab "$repo_root/deploy/helm/fdr" \
	    --namespace "$fdr_namespace" --create-namespace \
	    --values "$script_dir/fdr-values.yaml" \
	    --wait --timeout 5m

	if [ -n "$active_run_dir" ]; then
		verify_core
	else
		verify
	fi
}

down()
{
	require_tools
	require_acknowledgement
	if ! cluster_exists; then
		say "Kind cluster $cluster_name does not exist"
		return
	fi
	use_context
	say "Uninstalling FDR for graceful tracefs cleanup"
	helm uninstall fdr-lab --namespace "$fdr_namespace" --wait 2>/dev/null || true
	attempt=0
	while trace_instance_exists; do
		attempt=$((attempt + 1))
		if [ "$attempt" -ge 30 ]; then
			fail "trace instance still exists; inspect it before deleting the cluster"
		fi
		sleep 1
	done
	if [ ! -f "$cluster_owner_file" ] &&
	    [ "${FDR_LAB_DELETE_EXISTING:-}" != "yes" ]; then
		say "FDR was removed, but cluster $cluster_name was retained because this script did not create it"
		say "Set FDR_LAB_DELETE_EXISTING=yes to authorize deletion"
		return
	fi
	say "Deleting Kind cluster $cluster_name"
	kind delete cluster --name "$cluster_name"
	rm -f "$cluster_owner_file"
}

run_lab()
{
	require_tools
	require_acknowledgement
	begin_run
	trap failed_run 0 1 2 15
	up
	smoke
	trap failed_run 0 1 2 15
	down
	record_result "Graceful cleanup" "Helm uninstall removed the trace instance before cluster deletion"
	write_report PASSED
	trap - 0 1 2 15
	say "FULL LAB PASS: lifecycle completed and evidence retained at $active_run_dir"
}

grafana()
{
	require_tools
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	use_context
	say "Grafana: http://127.0.0.1:$grafana_port (admin / fdr-lab)"
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-grafana "$grafana_port:80"
}

usage()
{
	cat <<EOF
usage: $0 up|verify|smoke|run|collect|grafana|down

  up       build, create, install, and verify the lab
  verify   rerun non-destructive lab checks
  smoke    test rollout, degraded readiness, recovery, rotation, and screenshots
  run      create, run the full smoke workflow, and tear down safely
  collect  save diagnostics under .build/fdr-lab-artifacts
  grafana  expose Grafana at http://127.0.0.1:$grafana_port
  down     uninstall FDR, verify cleanup, and delete only $cluster_name

The up and down commands require:
  export FDR_LAB_ACKNOWLEDGE_HOST_KERNEL=yes
EOF
}

case ${1:-} in
up) up ;;
verify) verify ;;
smoke) smoke ;;
run) run_lab ;;
collect) collect ;;
grafana) grafana ;;
down) down ;;
*) usage; exit 2 ;;
esac
