#!/bin/sh
set -eu

cluster_name=${FDR_LAB_CLUSTER:-fdr-lab}
cluster_context="kind-${cluster_name}"
fdr_namespace=${FDR_LAB_NAMESPACE:-fdr-lab}
monitoring_namespace=${FDR_LAB_MONITORING_NAMESPACE:-monitoring}
monitoring_release=${FDR_LAB_MONITORING_RELEASE:-monitoring}
monitoring_chart_version=88.5.4
monitoring_repo_url=https://prometheus-community.github.io/helm-charts
monitoring_timeout=${FDR_LAB_MONITORING_TIMEOUT:-10m}
image_pull_timeout=${FDR_LAB_IMAGE_PULL_TIMEOUT:-15m}
fdr_image=fdr-lab:dev
grafana_port=${FDR_LAB_GRAFANA_PORT:-13000}
prometheus_port=${FDR_LAB_PROMETHEUS_PORT:-19090}

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../.." && pwd)
artifacts_root="$repo_root/.build/fdr-lab-artifacts"
cluster_owner_file="$artifacts_root/${cluster_name}.owned"
monitoring_cache="$artifacts_root/cache"
monitoring_chart="$monitoring_cache/kube-prometheus-stack-${monitoring_chart_version}.tgz"
forward_pid=

# Exact images rendered or generated by kube-prometheus-stack 88.5.4 with the
# focused deploy/kind/monitoring-values.yaml profile.
monitoring_images='
quay.io/kiwigrid/k8s-sidecar:2.10.1
docker.io/grafana/grafana:13.2.0
quay.io/prometheus-operator/prometheus-operator:v0.93.1
quay.io/prometheus-operator/prometheus-config-reloader:v0.93.1
quay.io/prometheus/prometheus:v3.14.0-distroless
'

say()
{
	printf '%s\n' "$*"
}

fail()
{
	printf 'error: %s\n' "$*" >&2
	exit 1
}

require_command()
{
	command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

require_tools()
{
	for tool in curl docker findmnt helm jq kind kubectl mktemp timeout; do
		require_command "$tool"
	done
}

retry()
{
	max_attempts=$1
	shift
	attempt=1
	while ! "$@"; do
		if [ "$attempt" -ge "$max_attempts" ]; then
			return 1
		fi
		attempt=$((attempt + 1))
		say "Retrying ($attempt/$max_attempts): $*"
		sleep 5
	done
}

require_acknowledgement()
{
	if [ "${FDR_LAB_ACKNOWLEDGE_HOST_KERNEL:-}" != "yes" ]; then
		fail "set FDR_LAB_ACKNOWLEDGE_HOST_KERNEL=yes after reading deploy/kind/README.md"
	fi
}

cluster_exists()
{
	kind get clusters 2>/dev/null | grep -Fxq "$cluster_name"
}

use_context()
{
	kubectl config use-context "$cluster_context" >/dev/null
}

prepare_monitoring_chart()
{
	mkdir -p "$monitoring_cache"
	repo_url=$(helm repo list -o json 2>/dev/null | jq -r \
	    'map(select(.name == "prometheus-community"))[0].url // ""' || true)
	if [ "$repo_url" = "$monitoring_repo_url" ]; then
		say "Using configured prometheus-community Helm repository"
	else
		retry 3 helm repo add prometheus-community "$monitoring_repo_url" \
		    --force-update
	fi
	if [ ! -s "$monitoring_chart" ]; then
		say "Caching kube-prometheus-stack chart $monitoring_chart_version"
		retry 3 helm pull prometheus-community/kube-prometheus-stack \
		    --version "$monitoring_chart_version" \
		    --destination "$monitoring_cache"
	fi
	helm show chart "$monitoring_chart" >/dev/null
}

load_monitoring_images()
{
	architecture=$(kubectl get nodes \
	    -o jsonpath='{.items[0].status.nodeInfo.architecture}')
	for image in $monitoring_images; do
		if docker image inspect "$image" >/dev/null 2>&1; then
			say "Using cached image $image"
		else
			say "Pulling monitoring image $image"
			retry 3 timeout "$image_pull_timeout" docker pull \
			    --platform "linux/$architecture" "$image"
		fi
		load_docker_image "$image"
	done
}

load_docker_image()
{
	image=$1
	architecture=$(kubectl get nodes \
	    -o jsonpath='{.items[0].status.nodeInfo.architecture}')
	nodes_to_load=
	for node in $(kind get nodes --name "$cluster_name"); do
		if ! docker exec "$node" crictl inspecti "$image" >/dev/null 2>&1; then
			nodes_to_load="$nodes_to_load $node"
		fi
	done
	if [ -z "$nodes_to_load" ]; then
		say "Image already loaded in Kind: $image"
		return
	fi

	archive=$(mktemp "$monitoring_cache/image.XXXXXX.tar")
	if ! docker save --output "$archive" "$image"; then
		rm -f "$archive"
		return 1
	fi
	for node in $nodes_to_load; do
		say "Loading $image into $node"
		if ! docker exec --privileged -i "$node" \
		    ctr --namespace=k8s.io images import \
		    --platform "linux/$architecture" --digests \
		    --snapshotter=overlayfs - <"$archive"; then
			rm -f "$archive"
			return 1
		fi
	done
	rm -f "$archive"
}

wait_for_http()
{
	url=$1
	attempt=0
	while ! curl --fail --silent --show-error "$url" >/dev/null 2>&1; do
		attempt=$((attempt + 1))
		if [ "$attempt" -ge 60 ]; then
			return 1
		fi
		sleep 1
	done
}

stop_forward()
{
	forward_pid=$1
	if kill -0 "$forward_pid" 2>/dev/null; then
		kill "$forward_pid" 2>/dev/null || true
		wait "$forward_pid" 2>/dev/null || true
	fi
}

cleanup_forward()
{
	if [ -n "$forward_pid" ]; then
		stop_forward "$forward_pid"
		forward_pid=
	fi
}

collect()
{
	require_tools
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	use_context
	timestamp=$(date -u +%Y%m%dT%H%M%SZ)
	destination="$artifacts_root/$timestamp"
	mkdir -p "$destination"

	kubectl get nodes -o wide >"$destination/nodes.txt" 2>&1 || true
	kubectl get all -A -o wide >"$destination/all-resources.txt" 2>&1 || true
	kubectl get events -A --sort-by=.lastTimestamp >"$destination/events.txt" 2>&1 || true
	kubectl -n "$fdr_namespace" describe daemonset fdr-lab \
	    >"$destination/fdr-daemonset.txt" 2>&1 || true
	kubectl -n "$fdr_namespace" logs daemonset/fdr-lab -c fdrd \
	    >"$destination/fdr.log" 2>&1 || true
	kubectl -n "$fdr_namespace" logs daemonset/fdr-lab \
	    -c tracefs-preflight >"$destination/preflight.log" 2>&1 || true
	kubectl -n "$fdr_namespace" get networkpolicy \
	    -o yaml >"$destination/fdr-networkpolicy.yaml" 2>&1 || true
	kubectl -n "$monitoring_namespace" get podmonitor,prometheusrule,configmap \
	    -l app.kubernetes.io/instance=fdr-lab -o yaml \
	    >"$destination/fdr-observability.yaml" 2>&1 || true
	kubectl -n "$fdr_namespace" exec daemonset/fdr-lab -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/metrics \
	    >"$destination/fdr-metrics.txt" 2>&1 || true
	kubectl -n "$fdr_namespace" exec daemonset/fdr-lab -c fdrd -- \
	    sh -ec 'wc -c /var/log/fdr/lab.log; tail -n 20 /var/log/fdr/lab.log' \
	    >"$destination/capture-sample.txt" 2>&1 || true
	kind export logs --name "$cluster_name" "$destination/kind" \
	    >/dev/null 2>&1 || true
	say "Artifacts: $destination"
}

verify()
{
	require_tools
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	use_context
	mkdir -p "$artifacts_root"
	trap cleanup_forward 0 1 2 15

	say "Waiting for FDR DaemonSet"
	kubectl -n "$fdr_namespace" rollout status daemonset/fdr-lab --timeout=180s
	pod=$(kubectl -n "$fdr_namespace" get pods \
	    -l app.kubernetes.io/instance=fdr-lab \
	    -o jsonpath='{.items[0].metadata.name}')
	[ -n "$pod" ] || fail "FDR pod was not found"

	say "Checking health, readiness, and metrics"
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/healthz | grep -Fxq ok
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/readyz | grep -Fxq ready
	metrics=$(kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- \
	    curl --fail --silent http://127.0.0.1:9119/metrics)
	printf '%s\n' "$metrics" | grep -q '^fdr_ready 1$'
	printf '%s\n' "$metrics" | grep -q '^fdr_trace_overruns_total '
	printf '%s\n' "$metrics" | grep -q '^fdr_trace_dropped_events_total '
	printf '%s\n' "$metrics" | grep -q '^fdr_trace_commit_overruns_total '

	say "Checking real trace output"
	kubectl -n "$fdr_namespace" exec "$pod" -c fdrd -- sh -ec '
	  attempt=0
	  while [ ! -s /var/log/fdr/lab.log ]; do
	    attempt=$((attempt + 1))
	    [ "$attempt" -lt 30 ] || exit 1
	    find /etc/fdr.d -maxdepth 1 -type f >/dev/null
	    sleep 1
	  done
	  grep -Eq "sched_(switch|wakeup)" /var/log/fdr/lab.log
	'

	[ -d /sys/kernel/tracing/instances/fdr-lab ] ||
	    fail "host trace instance was not created"

	say "Checking Prometheus discovery and rules"
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-kube-prometheus-prometheus \
	    "$prometheus_port:9090" >"$artifacts_root/prometheus-port-forward.log" 2>&1 &
	forward_pid=$!
	if ! wait_for_http "http://127.0.0.1:$prometheus_port/-/ready"; then
		stop_forward "$forward_pid"
		fail "Prometheus port-forward did not become ready"
	fi
	result=$(curl --fail --silent --get \
	    --data-urlencode 'query=fdr_ready' \
	    "http://127.0.0.1:$prometheus_port/api/v1/query")
	printf '%s' "$result" | jq -e '.status == "success" and (.data.result | length) > 0' \
	    >/dev/null
	rules=$(curl --fail --silent \
	    "http://127.0.0.1:$prometheus_port/api/v1/rules")
	printf '%s' "$rules" | jq -e \
	    '.data.groups | any(.name == "fdr.rules")' >/dev/null
	stop_forward "$forward_pid"
	forward_pid=

	say "Checking Grafana dashboard provisioning"
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-grafana "$grafana_port:80" \
	    >"$artifacts_root/grafana-port-forward.log" 2>&1 &
	forward_pid=$!
	if ! wait_for_http "http://127.0.0.1:$grafana_port/api/health"; then
		stop_forward "$forward_pid"
		fail "Grafana port-forward did not become ready"
	fi
	dashboards=$(curl --fail --silent --user admin:fdr-lab \
	    "http://127.0.0.1:$grafana_port/api/search?query=FDR")
	printf '%s' "$dashboards" | jq -e \
	    'any(.uid == "fdr-kernel-recorder")' >/dev/null
	stop_forward "$forward_pid"
	forward_pid=
	trap - 0 1 2 15

	say "LAB PASS: FDR captured real host-kernel events and is visible in Prometheus and Grafana"
}

up()
{
	require_tools
	require_acknowledgement
	[ "$(findmnt -n -o FSTYPE -T /sys/kernel/tracing)" = "tracefs" ] ||
	    fail "/sys/kernel/tracing is not a tracefs mount"
	tracefs_options=$(findmnt -n -o OPTIONS -T /sys/kernel/tracing)
	printf '%s\n' "$tracefs_options" | tr ',' '\n' | grep -Fxq rw ||
	    fail "/sys/kernel/tracing is not mounted read-write"
	mkdir -p "$artifacts_root"

	say "Building local image $fdr_image"
	docker build --provenance=false -t "$fdr_image" \
	    -f "$repo_root/deploy/kubernetes/Dockerfile" "$repo_root"
	prepare_monitoring_chart

	if ! cluster_exists; then
		say "Creating Kind cluster $cluster_name"
		kind create cluster --name "$cluster_name" \
		    --config "$script_dir/kind-config.yaml" --wait 180s
		touch "$cluster_owner_file"
	else
		if [ ! -f "$cluster_owner_file" ] &&
		    [ "${FDR_LAB_REUSE_EXISTING:-}" != "yes" ]; then
			fail "cluster $cluster_name already exists; set FDR_LAB_REUSE_EXISTING=yes to use it without ownership"
		fi
		say "Using existing Kind cluster $cluster_name"
	fi
	use_context
	load_docker_image "$fdr_image"
	load_monitoring_images

	say "Installing kube-prometheus-stack $monitoring_chart_version"
	helm upgrade --install "$monitoring_release" \
	    "$monitoring_chart" \
	    --namespace "$monitoring_namespace" --create-namespace \
	    --values "$script_dir/monitoring-values.yaml" \
	    --wait --timeout "$monitoring_timeout"

	say "Installing FDR"
	helm upgrade --install fdr-lab "$repo_root/deploy/helm/fdr" \
	    --namespace "$fdr_namespace" --create-namespace \
	    --values "$script_dir/fdr-values.yaml" \
	    --wait --timeout 5m

	verify
}

down()
{
	require_tools
	require_acknowledgement
	if ! cluster_exists; then
		say "Kind cluster $cluster_name does not exist"
		return
	fi
	use_context
	say "Uninstalling FDR for graceful tracefs cleanup"
	helm uninstall fdr-lab --namespace "$fdr_namespace" --wait 2>/dev/null || true
	attempt=0
	while [ -d /sys/kernel/tracing/instances/fdr-lab ]; do
		attempt=$((attempt + 1))
		if [ "$attempt" -ge 30 ]; then
			fail "trace instance still exists; inspect it before deleting the cluster"
		fi
		sleep 1
	done
	if [ ! -f "$cluster_owner_file" ] &&
	    [ "${FDR_LAB_DELETE_EXISTING:-}" != "yes" ]; then
		say "FDR was removed, but cluster $cluster_name was retained because this script did not create it"
		say "Set FDR_LAB_DELETE_EXISTING=yes to authorize deletion"
		return
	fi
	say "Deleting Kind cluster $cluster_name"
	kind delete cluster --name "$cluster_name"
	rm -f "$cluster_owner_file"
}

grafana()
{
	require_tools
	cluster_exists || fail "Kind cluster $cluster_name does not exist"
	use_context
	say "Grafana: http://127.0.0.1:$grafana_port (admin / fdr-lab)"
	kubectl -n "$monitoring_namespace" port-forward \
	    service/${monitoring_release}-grafana "$grafana_port:80"
}

usage()
{
	cat <<EOF
usage: $0 up|verify|collect|grafana|down

  up       build, create, install, and verify the lab
  verify   rerun non-destructive lab checks
  collect  save diagnostics under .build/fdr-lab-artifacts
  grafana  expose Grafana at http://127.0.0.1:$grafana_port
  down     uninstall FDR, verify cleanup, and delete only $cluster_name

The up and down commands require:
  export FDR_LAB_ACKNOWLEDGE_HOST_KERNEL=yes
EOF
}

case ${1:-} in
up) up ;;
verify) verify ;;
collect) collect ;;
grafana) grafana ;;
down) down ;;
*) usage; exit 2 ;;
esac
