{{- if and .Values.http.enabled .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "fdr.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.monitoring.podMonitor.namespace }}
  labels:
    {{- include "fdr.labels" . | nindent 4 }}
    {{- with .Values.monitoring.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "fdr.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.podMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout }}
{{- end }}
